# Agent configuration for multi-agent chatbot system

router_agent:
  model: "gpt-3.5-turbo"
  temperature: 0.1
  max_tokens: 500
  confidence_threshold: 0.8
  enable_context_aware_routing: true
  max_conversation_history: 10

faq_agent:
  model: "gpt-3.5-turbo"
  temperature: 0.2
  vector_store: "faiss"
  similarity_threshold: 0.7
  max_search_results: 5
  enable_related_questions: true

sales_agent:
  model: "gpt-3.5-turbo"
  temperature: 0.3
  enable_lead_qualification: true
  enable_product_recommendations: true
  crm_integration: false
  lead_scoring_threshold: 0.6

tech_support_agent:
  model: "gpt-4"
  temperature: 0.1
  enable_escalation: true
  escalation_threshold: 3  # Number of failed attempts before escalation
  ticket_system_integration: false
  enable_guided_troubleshooting: true

# Global settings
global:
  default_timeout_ms: 30000
  max_concurrent_conversations: 100
  enable_metrics: true
  log_level: "INFO"
  
# AMP network settings
amp:
  registry_url: "http://localhost:8000"
  transport_type: "http"
  heartbeat_interval: 30
  auto_reconnect: true
  
# Security settings
security:
  enable_authentication: true
  session_timeout: 3600  # 1 hour
  rate_limit_per_hour: 100