# CrewAI Crew Configuration for Research Assistant Network

# Main Research Crew Configuration
research_crew:
  name: "Comprehensive Research Crew"
  description: "Multi-agent crew for comprehensive research workflows"
  process: "sequential"  # sequential, hierarchical
  verbose: true
  memory: true
  max_execution_time: 3600  # 1 hour in seconds
  max_rpm: 20  # Requests per minute limit
  
  # Agent configuration
  agents:
    search_agent:
      role: "Senior Research Search Specialist"
      max_iter: 5
      max_execution_time: 600  # 10 minutes
      temperature: 0.1
      
    analysis_agent:
      role: "Expert Content Analysis Researcher"
      max_iter: 3
      max_execution_time: 900  # 15 minutes
      temperature: 0.1
      
    verification_agent:
      role: "Senior Fact Verification Specialist"
      max_iter: 4
      max_execution_time: 1200  # 20 minutes
      temperature: 0.05
      
    synthesis_agent:
      role: "Master Research Synthesis Expert"
      max_iter: 3
      max_execution_time: 1800  # 30 minutes
      temperature: 0.3

# Fact-Checking Specialized Crew
fact_check_crew:
  name: "Fact Verification Crew"
  description: "Specialized crew for comprehensive fact-checking workflows"
  process: "hierarchical"
  verbose: true
  memory: true
  max_execution_time: 1800  # 30 minutes
  max_rpm: 15
  
  agents:
    primary_verifier:
      role: "Lead Fact Verification Specialist"
      max_iter: 5
      max_execution_time: 900
      temperature: 0.05
      
    source_validator:
      role: "Source Credibility and Validation Expert"
      max_iter: 3
      max_execution_time: 600
      temperature: 0.1
      
    claims_analyst:
      role: "Claims Analysis and Decomposition Specialist"
      max_iter: 3
      max_execution_time: 600
      temperature: 0.2
      
    evidence_synthesizer:
      role: "Evidence Synthesis and Verdict Specialist"
      max_iter: 2
      max_execution_time: 600
      temperature: 0.15

# Content Creation Crew
content_creation_crew:
  name: "Content Creation and Synthesis Crew"
  description: "Specialized crew for content synthesis and report generation"
  process: "sequential"
  verbose: true
  memory: true
  max_execution_time: 2400  # 40 minutes
  max_rpm: 12
  
  agents:
    content_strategist:
      role: "Senior Content Strategy and Planning Expert"
      max_iter: 2
      max_execution_time: 600
      temperature: 0.3
      
    research_writer:
      role: "Expert Research Writer and Content Developer"
      max_iter: 4
      max_execution_time: 1200
      temperature: 0.4
      
    citation_specialist:
      role: "Citation Management and Academic Standards Expert"
      max_iter: 2
      max_execution_time: 600
      temperature: 0.1
      
    quality_editor:
      role: "Senior Quality Assurance and Editorial Expert"
      max_iter: 3
      max_execution_time: 600
      temperature: 0.2

# Quick Research Crew (for simple queries)
quick_research_crew:
  name: "Quick Research Crew"
  description: "Streamlined crew for rapid research tasks"
  process: "sequential"
  verbose: false
  memory: false
  max_execution_time: 600  # 10 minutes
  max_rpm: 30
  
  agents:
    quick_researcher:
      role: "Quick Research Specialist"
      max_iter: 2
      max_execution_time: 300
      temperature: 0.2

# Global Crew Settings
global_settings:
  # Language model settings
  llm:
    provider: "openai"  # openai, anthropic, azure
    model: "gpt-4"
    temperature: 0.1
    max_tokens: 2000
    timeout: 30
    
  # Retry settings
  retry:
    max_retries: 3
    retry_delay: 1.0
    backoff_factor: 2.0
    
  # Memory settings
  memory:
    provider: "local"  # local, redis, postgres
    max_entries: 1000
    ttl_hours: 24
    
  # Logging settings
  logging:
    level: "INFO"
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    file: "logs/crew_execution.log"
    max_file_size: "10MB"
    backup_count: 5

# Performance tuning
performance:
  # Concurrency settings
  max_concurrent_tasks: 3
  max_concurrent_agents: 2
  
  # Resource limits
  memory_limit_mb: 2048
  cpu_limit_percent: 80
  
  # Optimization flags
  enable_caching: true
  cache_ttl_minutes: 30
  enable_task_batching: true
  batch_size: 5